// ABOUTME: tsup configuration for building Obsidian plugin as single main.js file
// ABOUTME: Replaces esbuild setup with modern bundling and development workflow

import { defineConfig } from 'tsup'

export default defineConfig({
	entry: ['src/plugin.ts'],
	format: 'iife',
	target: 'es2020',
	globalName: 'plugin',
	outDir: '.',
	outExtension: () => ({ js: '.js' }),
	platform: 'browser',
	external: ['obsidian'],
	noExternal: [],
	minify: process.env.NODE_ENV === 'production',
	sourcemap: process.env.NODE_ENV !== 'production',
	clean: false,
	esbuildOptions: (options) => {
		options.external = ['obsidian']
		return options
	},
	define: {
		'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development')
	},
	banner: {
		js: '/*\nTHIS IS A GENERATED/BUNDLED FILE BY TSUP\nif you want to view the source visit the plugins github repository\n*/'
	}
})