name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build plugin
      run: npm run build

    - name: Create release package
      run: |
        mkdir release
        cp main.js manifest.json styles.css release/
        cd release && zip -r ../nv-switcher-${{ github.ref_name }}.zip .

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          nv-switcher-${{ github.ref_name }}.zip
          main.js
          manifest.json
          styles.css
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}